name: NimbleServer
version: 0.0.12
description: Nimbles server plugins
author: nimble

main: de.nimble.server.NimbleServer

commands:
  enchantments:
    usage: /<command>
    description: Enchantment command
    aliases: [ec]
  items:
    usage: /<command>
    description: item command
    aliases: [ic]