name: NimbleServer
version: 0.0.15
description: Nimbles server plugins
author: nimble
api-version: 1.15
main: de.nimble.server.NimbleServer

commands:
  enchantments:
    usage: /<command>
    description: Enchantment command
    aliases: [ec]
  items:
    usage: /<command>
    description: item command
    aliases: [ic]